baseurl = "http://www.zankyou.tk/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "Creative portfolio"
[params]
copyright = "&copy;2016 Your name or company"
description = "Describe your website"
email = "you@yoursite.com"
sidebarAbout = ["I am a creative illustrator and graphic designer with more than 10 years of experience.", "Originally from Toronto, currently based in London."]
style = "blue"
[params.social]
email = "email@example.com"
facebook = "full page or profile url in facebook"
instagram = "full profile url in instagram"
twitter = "full profile url in twitter"
[[params.navlinks]]
home = true
name = "Home"
url = "home/"
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
